Aizad/FEQ-1442/Input Component
deriv-com/ui pull request #13
Opened 2024-01-19 10:00 UTC by aizad-deriv

Created Input component with base stylings.
This input component can be extended to Text field, Password Field and Text Area.
This input component supports different states: `active`, `disabled`, `success` &`error`.

2024-01-22 01:24 UTC, shayan-deriv commented on lib/components/Input/index.tsx
> +  helpLineMessage?: string;
not sure if the PR is still in progress but this is not used . I guess it's for the things like error/warning messages that goes under the input right? @aizad-deriv

2024-01-24 05:04 UTC, shayan-deriv reviewed
I just added these suggestions, so we have them on the top suggestion list

2024-01-24 05:04 UTC, shayan-deriv commented on lib/components/Input/index.tsx
> +  ...rest
```suggestion
  className,
  isHelperMessageDisabled,
  ...rest
```

2024-01-24 05:04 UTC, shayan-deriv commented on lib/components/Input/index.tsx
> +          { className: rest.className },
```suggestion
          { className: className },
```

2024-01-24 05:04 UTC, shayan-deriv commented on lib/components/Input/index.tsx
> +            disabled={rest.disabled}
```suggestion
            disabled={isHelperMessageDisabled}
```

2024-01-24 05:19 UTC, shahzaib-deriv commented on lib/components/Input/index.tsx
> +  ...rest
why do we need `isHelperMessageDisabled`?

2024-01-24 05:20 UTC, shahzaib-deriv commented on lib/components/Input/index.tsx
> +            disabled={rest.disabled}
Helpermessage is relying on single disabled flag for the input. It is being used for setting the color to be synced

2024-01-24 05:21 UTC, aizad-deriv commented on lib/components/Input/index.tsx
> +            disabled={rest.disabled}
I agree with @shahzaib-deriv the disabled message all depends on the input field same goes and so on.

2024-01-24 05:22 UTC, shahzaib-deriv requested changes

2024-01-24 05:22 UTC, shahzaib-deriv commented on lib/components/Input/index.tsx
> +          { className: rest.className },
```suggestion
          "deriv-input--field", rest.className,
```

2024-01-24 05:23 UTC, aizad-deriv commented on lib/components/Input/index.tsx
> +          { className: rest.className },
resolved

2024-01-24 05:27 UTC, aizad-deriv commented on lib/components/Input/index.tsx
> +  ...rest
In my opinion this doesn't bring any sort of value to the component because we are repeating over and over again. The helper message should behave the same as the input field.

2024-01-24 05:29 UTC, aizad-deriv commented on lib/components/Input/index.tsx
> +          { className: rest.className },
Already resolved in the new commit 👍🏼

2024-01-24 05:32 UTC, shayan-deriv commented on lib/components/Input/index.tsx
> +  ...rest
@aizad-deriv @shahzaib-deriv you're right. I just meant that since we were using it like `disabled={rest.disabled}` then we better get it out of the `rest` object. that's it.

2024-01-24 05:36 UTC, shahzaib-deriv commented on lib/components/Input/index.tsx
> +      )}
```suggestion
      {hasRightPlaceholder && (
        <div className="deriv-input--right-content">{hasRightPlaceholder}</div>
      )}
```

`hasRightPlaceholder` seems more like a boolean and IMO the content should be called only `rightPlaceholder` or something similar

2024-01-24 05:37 UTC, shahzaib-deriv commented on lib/components/Input/index.tsx
> +  ...rest
@shayan-deriv Got your point. However using it from rest has no harm tho. Also @aizad-deriv already fixed it 👍

2024-01-24 05:57 UTC, shahzaib-deriv approved these changes

2024-01-24 06:28 UTC, shayan-deriv approved these changes

2024-01-24 06:30 UTC, merged