Ako/ Add language switcher
deriv-com/ui pull request #198
Opened 2024-05-17 06:13 UTC by ali-hosseini-deriv

This is to add language switcher component.
The desktop mode can be visible in storybook and the mobile is implemented as part of playground.

2024-05-17 06:23 UTC, niloofar-deriv commented on src/components/AppLayout/Drawer/DrawerHeader/DrawerHeader.scss
> +        justify-content: space-between;
Do we need this?

2024-05-17 06:23 UTC, niloofar-deriv commented on src/main.ts
> +export { DesktopLanguagesModal } from "./components/AppLayout/LanguagesModal/DesktopLanguagesModal";
Please export these in `src/components/AppLayout/index.ts`

```
export { DesktopLanguagesModal } from "./LanguagesModal/DesktopLanguagesModal";
export { MobileLanguagesDrawer } from "./LanguagesModal/MobileLanguagesDrawer";
```

2024-05-17 06:23 UTC, niloofar-deriv commented on src/main.ts
>      PlatformSwitcherItem,
```suggestion
    PlatformSwitcherItem,
    DesktopLanguagesModal,
    MobileLanguagesDrawer
```

2024-05-17 06:23 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/MobileLanguagesDrawer.tsx
> +                            <Button
Please replace this with <LanguageItem /> component

2024-05-17 06:23 UTC, niloofar-deriv commented on src/components/AppLayout/Drawer/DrawerHeader/DrawerHeader.scss
>  }
```suggestion
}

```

2024-05-17 06:28 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +        color="black"
I guess this is redundant 
```suggestion
       
```

2024-05-17 06:30 UTC, ali-hosseini-deriv commented on src/components/AppLayout/Drawer/DrawerHeader/DrawerHeader.scss
> +        justify-content: space-between;
yess that's for drawer header items to be aligned

2024-05-17 07:02 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/DesktopLanguagesModal.tsx
> +    languages: {
```suggestion
    languages: ComponentProps<typeof LanguageItem>['language'][]
```

2024-05-17 07:03 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +    display_name: string | ReactElement;
```suggestion
    displayName: string;
```

2024-05-17 07:03 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +    icon: IconTypes;
```suggestion
    Icon: ReactNode;
```

2024-05-17 07:04 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +    icon: IconTypes;
Just go inside Button component and add this 😁 
`icon?: ReactElement | ReactNode;`

it dose not break anything believe me 😬

2024-05-17 07:08 UTC, niloofar-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +        className="languages__body-button"
```suggestion
        className="languages-body__button"
```

2024-05-17 08:54 UTC, ali-hosseini-deriv commented on src/components/AppLayout/LanguagesModal/MobileLanguagesDrawer.tsx
> +                            <Button
done

2024-05-17 08:55 UTC, ali-hosseini-deriv commented on src/main.ts
>      PlatformSwitcherItem,
done

2024-05-17 08:55 UTC, ali-hosseini-deriv commented on src/main.ts
> +export { DesktopLanguagesModal } from "./components/AppLayout/LanguagesModal/DesktopLanguagesModal";
done

2024-05-17 08:58 UTC, ali-hosseini-deriv commented on src/components/AppLayout/Drawer/DrawerHeader/DrawerHeader.scss
>  }
done

2024-05-17 08:59 UTC, ali-hosseini-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +        color="black"
done

2024-05-17 09:02 UTC, ali-hosseini-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +    icon: IconTypes;
sure :-D 
done

2024-05-17 09:02 UTC, ali-hosseini-deriv commented on src/components/AppLayout/LanguagesModal/LanguageItem.tsx
> +    display_name: string | ReactElement;
done

2024-05-17 12:08 UTC, prince-deriv requested changes

2024-05-17 12:08 UTC, prince-deriv commented on playground/index.tsx
> +    const [selectedLang, setSelectedLang] = React.useState("en");
```suggestion
    const [selectedLanguage, setSelectedLanguage] = React.useState("en");
```

2024-05-17 12:08 UTC, prince-deriv commented on playground/index.tsx
> +    const [isLanguageDrawerOpen, setIsLanguagesDrawerOpen] =
```suggestion
    const [isLanguagesDrawerOpen, setIsLanguagesDrawerOpen] =
```

2024-05-17 12:08 UTC, prince-deriv commented on playground/index.tsx
> +    console.log(SelectedLanguageIcon);
Do we still need to console?

2024-05-20 03:41 UTC, niloofar-deriv approved these changes
LGTM 👍

2024-05-20 03:43 UTC, niloofar-deriv commented on playground/index.tsx
> +    console.log(SelectedLanguageIcon);
@prince-deriv the playground file is not a parts of build and it's just a test file for ourselves so it dose not matter how we are naming variable and states and the rest of the things

2024-05-20 04:03 UTC, ali-hosseini-deriv commented on playground/index.tsx
> +    console.log(SelectedLanguageIcon);
that's right, anyways I've done the suggested changes

2024-05-20 04:03 UTC, ali-hosseini-deriv commented on playground/index.tsx
> +    const [isLanguageDrawerOpen, setIsLanguagesDrawerOpen] =
done

2024-05-20 05:20 UTC, niloofar-deriv approved these changes

2024-05-20 07:28 UTC, prince-deriv approved these changes

2024-05-20 08:56 UTC, shayan-deriv approved these changes

2024-05-20 08:56 UTC, merged