Niloofar/ Submenu component
deriv-com/ui pull request #214
Opened 2024-06-07 07:52 UTC by niloofar-deriv

https://github.com/deriv-com/ui/assets/93518187/4ce5d14c-67c0-4abd-a02d-0ca654a82124

2024-06-07 08:04 UTC, ali-hosseini-deriv requested changes
there is a padding or margin between the icon and the text in production. dont we need that?

2024-06-07 08:05 UTC, ali-hosseini-deriv approved these changes

2024-06-07 08:08 UTC, farrah-deriv approved these changes

2024-06-07 08:18 UTC, niloofar-deriv commented
> there is a padding or margin between the icon and the text in production. dont we need that?

Base on our discussion since this is a ui library I don't want to hard code these sizes so I added some props and customer would have the freedom to set the sizes

2024-06-07 08:23 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +export const Submenu = ({
```suggestion
export const SubMenu = ({
```
also for the rest please 🙏

2024-06-07 08:24 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /__tests__/Submenu.spec.tsx
> +        // Open the submenu
do we need this? 🤔

2024-06-07 08:26 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +            </button>
why do we have this? 
it should be a isolated component controlled by the consumer using `isOpen` prop

2024-06-07 09:46 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +    isOpen,
```suggestion
    isOpen,
    ...rest
```

2024-06-07 09:46 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +            className={clsx("submenu", { submenu_exit: isClosing }, className)}
```suggestion
            className={clsx("submenu", { submenu_exit: isClosing }, className)} {...rest}
```

2024-06-07 10:15 UTC, farrah-deriv approved these changes

2024-06-08 08:24 UTC, shayan-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +    const [isClosing, setIsClosing] = useState(false);
an reason for having two states ?
one should be enough.just like the [drawer](https://github.com/deriv-com/ui/blob/main/src/components/AppLayout/Drawer/index.tsx) component.

2024-06-10 02:38 UTC, niloofar-deriv commented on src/components/AppLayout/Submenu /index.tsx
> +    const [isClosing, setIsClosing] = useState(false);
No need for that, thanks for noticing this. I'll remove it 🙏

2024-06-10 02:54 UTC, shayan-deriv approved these changes

2024-06-10 02:54 UTC, merged