Aizad/FEQ-2441/ Implement new Tooltip with Popper.js
deriv-com/ui pull request #223
Opened 2024-07-03 06:34 UTC by aizad-deriv

## Changes
- Installed Popper.js inside project
- Created new Tooltip component with Popper.js implementation

2024-07-03 09:46 UTC, yashim-deriv approved these changes

2024-07-03 09:46 UTC, yashim-deriv commented on src/components/Tooltip/index.tsx
> +export const Tooltip = <T extends AsElement>({
At one point the user might need some ref to be passed using `forwardRef` - it will be good to add this support. Since internally you are assigning a ref as well you can use the useImperativeHandle: https://react.dev/reference/react/useImperativeHandle to handle this ref so that ref that is forwarded and the internal ref is in sync

2024-07-03 09:47 UTC, yashim-deriv commented on src/components/Tooltip/index.tsx
> +    const [referenceElement, setReferenceElement] = useState(null);
```suggestion
    const [referenceElement, setReferenceElement] = useRef(null);
```

2024-07-03 09:47 UTC, yashim-deriv commented on src/components/Tooltip/index.tsx
> +    const [popperElement, setPopperElement] = useState<HTMLDivElement | null>(
```suggestion
    const [popperElement, setPopperElement] = useRef<HTMLDivElement | null>(
```

2024-07-03 09:48 UTC, yashim-deriv commented on src/components/Tooltip/index.tsx
> +    const [arrowElement, setArrowElement] = useState<HTMLDivElement | null>(
```suggestion
    const [arrowElement, setArrowElement] = useRef<HTMLDivElement | null>(
```

2024-07-04 03:14 UTC, niloofar-deriv commented on package.json
>          "react-tiny-popover": "^8.0.4"
Could u pls remove this as well
also TooltipMenuIcon component cause we are not using them anywhere 
```suggestion
        
```

2024-07-04 03:15 UTC, niloofar-deriv commented on src/components/Tooltip/index.tsx
> +    children: ReactNode;
```suggestion
```

2024-07-04 03:16 UTC, niloofar-deriv commented on src/components/Tooltip/index.tsx
> +    children: ReactNode;
Please use PropsWithChildren instead of defining the type here

2024-07-04 03:17 UTC, aizad-deriv commented on src/components/Tooltip/index.tsx
> +export const Tooltip = <T extends AsElement>({
@yashim-deriv I don't believe it's necessary to add ref because the ref is assigned to the values from the `usePopper` hook.

2024-07-04 03:18 UTC, niloofar-deriv commented on src/components/Tooltip/index.tsx
> +}: TooltipProps<T>) => {
```suggestion
}: PropsWithChildren<TooltipProps<T>>) => {
```

2024-07-04 03:39 UTC, yashim-deriv requested changes
I will swing by with regards the ref

2024-07-04 08:18 UTC, niloofar-deriv approved these changes

2024-07-05 02:40 UTC, yashim-deriv commented on src/components/Tooltip/index.tsx
> +export const Tooltip = <T extends AsElement>({
i will swing by

2024-07-05 03:19 UTC, shayan-deriv approved these changes

2024-07-05 03:20 UTC, yashim-deriv approved these changes

2024-07-05 03:28 UTC, niloofar-deriv approved these changes

2024-07-05 03:31 UTC, merged