[FEQ]Yaswanth/FEQ-1448-Added Text Area Component
deriv-com/ui pull request #57
Opened 2024-02-02 12:50 UTC by yaswanth-deriv

Added a textarea component within the deriv/ui package, making it accessible for use across various packages by importing it directly from this library.
<img width="1198" alt="Screenshot 2024-02-02 at 4 49 56 PM" src="https://github.com/deriv-com/ui/assets/121096908/6ec18fbb-8a0f-4432-985c-4809eaf28550">

2024-02-05 03:30 UTC, thisyahlen-deriv commented on lib/components/TextArea/index.tsx
> +    value,
Lets expose all the props including className to <textarea

2024-02-05 03:32 UTC, shahzaib-deriv requested changes

2024-02-05 03:32 UTC, shahzaib-deriv commented on lib/components/TextArea/index.tsx
> +    const [currentValue, setCurrentValue] = useState(value);
value shouldn't be kept inside the component

2024-02-05 03:32 UTC, shahzaib-deriv commented on lib/components/TextArea/index.tsx
> +                        {currentValue?.length || 0}/{maxLength}
to access the length, the value prop can be used directly to calculate the length rather than keeping the state inside this component

2024-02-05 03:32 UTC, shahzaib-deriv commented on lib/components/TextArea/index.tsx
> +                value={currentValue}
we should expose each an every attribute available for textarea just like we did for the input component

2024-02-05 03:44 UTC, hasan-deriv commented on lib/components/TextArea/TextArea.scss
> +                color: #ec3f3f;
Is it possible to move all the color to css custom properties?

2024-02-06 02:25 UTC, aizad-deriv commented on lib/components/TextArea/index.tsx
> +import React, { HtmlHTMLAttributes, useState } from 'react';
I'm not sure if it's doable but why is this component not extending from the existing `<Input/>` component? There are classNames and similar props with the same use cases. The only difference it has a bigger footprint.

2024-02-08 04:21 UTC, aizad-deriv commented on lib/components/TextArea/TextArea.scss
> +        height: 9.6rem;
I'm not sure about using rem values. From my knowledge we haven' set the `1rem` to `10px`. If it is already configured you can just ignore if not then I suggest you to use to `px` instead.

2024-02-08 04:24 UTC, aizad-deriv commented on lib/components/ToggleSwitch/index.tsx
> +    style?: React.CSSProperties;
if you want to take it to the next level you can always reference the Input component by:

```suggestion
    wrapperClassName?: ComponentProps<typeof Input>['wrapperClassName'];
    className?: ComponentProps<typeof Input>['className'];
    wrapperStyle?: React.CSSProperties;
    style?: React.CSSProperties;
```

2024-02-08 07:18 UTC, yaswanth-deriv commented on lib/components/ToggleSwitch/index.tsx
> +    style?: React.CSSProperties;
Yes I can add this one..Thanks

2024-02-08 07:19 UTC, yaswanth-deriv commented on lib/components/TextArea/TextArea.scss
> +        height: 9.6rem;
Yes rem is configured..

2024-02-13 05:52 UTC, shayan-deriv commented on lib/components/TextArea/TextArea.scss
> +                color: #ec3f3f;
@hasan-deriv we will refine the styles later

2024-02-13 05:53 UTC, shayan-deriv approved these changes

2024-02-13 05:53 UTC, merged