[FEQ]Yaswanth/FEQ-1753_Able to control dropdown value by local state
deriv-com/ui pull request #90
Opened 2024-02-21 08:57 UTC by yaswanth-deriv

With this changes we can able to control dropdown value by local state

2024-02-21 11:05 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +    selectedVal?: InputProps["value"];
```suggestion
    selectedItem?: InputProps["value"];
```
or `selecteValue` ? 🤔

2024-02-22 03:56 UTC, wojciech-deriv commented on lib/components/Dropdown/index.tsx
>      value,
whats the difference between value and selectedValue?

2024-02-22 07:06 UTC, markwylde-deriv requested changes
value and selectedValue is confusing. Can we name these to something better?

2024-02-22 07:31 UTC, yaswanth-deriv commented on lib/components/Dropdown/index.tsx
>      value,
Yeah I will change names.SelecedVal prop is using to able to control dropdown by internal state.I will change name to avoid confusion

2024-02-23 02:44 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +    listVariant?:"normalList" | "doubleList";
just a suggestion:
```suggestion
    listVariant?:"normal" | "detailed";
```

2024-02-23 02:44 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> + * @param {string} props.listVariant - Variant of the list in dropdown ('normalList' or 'doubleList').
```suggestion
 * @param {string} props.listVariant - Variant of the list in dropdown ('normal' or 'detailed').
```

2024-02-23 02:45 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +    listVariant="normalList",
```suggestion
    listVariant="normal",
```

2024-02-23 02:45 UTC, shahzaib-deriv commented on lib/components/Dropdown/index.tsx
> + * @param {string} props.initialValue - Selected value from the list.
looking at the description of `initialValue` looks like it'll be selected value and the name doesn't go in a way that it defines the selected value

2024-02-23 02:46 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                    value={initialValue?initialValue:value}
```suggestion
                    value={ initialValue ?? value }
```

2024-02-23 02:48 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                                "deriv-dropdown__item--doubleList":
```suggestion
                                "deriv-dropdown__item--detailed":
```

2024-02-23 02:49 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                    {noResults && <li className="no-results-found">No results found</li>}
```suggestion
                    {noResults && <li className="no-results-found">{noResultMessage}</li>}
```
can we add a props called `noResultMessage` ? because they want to pass the message

2024-02-23 02:49 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                               listVariant==="doubleList"&& item?.shortcut &&
```suggestion
                               listVariant==="detailed"&& item?.shortcut &&
```

2024-02-23 02:50 UTC, shayan-deriv commented on lib/components/Dropdown/Dropdown.scss
> +        &--doubleList {
```suggestion
        &--detailed {
```

2024-02-23 02:50 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                                listVariant==="doubleList"
```suggestion
                                listVariant==="detailed"
```

2024-02-23 03:13 UTC, shayan-deriv commented on lib/components/Dropdown/index.tsx
> +                    {noResults && <li className="no-results-found">No results found</li>}
I noticed that inside the design file it's like this:
![image](https://github.com/deriv-com/ui/assets/100833613/5499a613-6cf0-4e3e-81db-09b58be8f4a1)

but you need to modify it and include the query inside the message like the design

so maybe we don't need to pass any message from outside 🤔

2024-02-28 03:04 UTC, closed without merging